package com.talabat.core.featureflag.domain.flags.pay;

import com.talabat.core.featureflag.domain.flags.pay.PayFeatureFlagConstants;
import com.talabat.core.fwfprojectskeys.domain.FWFKey;
import java.util.List;
import kotlin.Metadata;
import kotlin.jvm.functions.Function0;
import kotlin.jvm.internal.Lambda;
import kotlin.sequences.Sequence;
import org.jetbrains.annotations.NotNull;

@Metadata(d1 = {"\u0000\f\n\u0000\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0000\u0010\u0000\u001a\b\u0012\u0004\u0012\u00020\u00020\u0001H\n¢\u0006\u0002\b\u0003"}, d2 = {"<anonymous>", "", "Lcom/talabat/core/fwfprojectskeys/domain/FWFKey;", "invoke"}, k = 3, mv = {1, 6, 0}, xi = 48)
public final class PayFeatureFlagConstants$PayFlags$1 extends Lambda implements Function0<List<? extends FWFKey>> {
    public static final PayFeatureFlagConstants$PayFlags$1 INSTANCE = new PayFeatureFlagConstants$PayFlags$1();

    public PayFeatureFlagConstants$PayFlags$1() {
        super(0);
    }

    @NotNull
    public final List<FWFKey> invoke() {
        PayFeatureFlagConstants payFeatureFlagConstants = PayFeatureFlagConstants.INSTANCE;
        Sequence plus = SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(CollectionsKt___CollectionsKt.asSequence(payFeatureFlagConstants.getAllCountriesFlag(PayFeatureFlagConstants.CARD_MANAGEMENT)), payFeatureFlagConstants.getAllCountriesFlag(PayFeatureFlagConstants.TOP_UP)), payFeatureFlagConstants.getAllCountriesFlag(PayFeatureFlagConstants.SEND_GIFT)), payFeatureFlagConstants.getAllCountriesFlag(PayFeatureFlagConstants.EXPIRING_CREDIT)), payFeatureFlagConstants.getAllCountriesFlag(PayFeatureFlagConstants.CASHBACK)), payFeatureFlagConstants.getAllCountriesFlag(PayFeatureFlagConstants.SET_DEFAULT_CARD)), payFeatureFlagConstants.getAllCountriesFlag(PayFeatureFlagConstants.ADD_CARD)), payFeatureFlagConstants.getAllCountriesFlag(PayFeatureFlagConstants.DELETE_CARD)), payFeatureFlagConstants.getAllCountriesFlag("")), payFeatureFlagConstants.getAllCountriesFlag(PayFeatureFlagConstants.CARD_HOLDER_NAME)), payFeatureFlagConstants.getAllCountriesFlag(PayFeatureFlagConstants.WALLET_TIP_RIDER_ON_ORDER_CONFIRMATION_SCREEN)), payFeatureFlagConstants.getRiderTipFlags()), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_OMANET_FORCE_CVV), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_ENABLE_KNET_STATUS_CHECK), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_ENABLE_QPAY_PAYMENT), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_BALANCE_API_ENABLED_ON_CHECKOUT_SCREEN), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_CHECKOUT_OUT_TIME_OUT_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_BENEFIT_BIN_DETAIL), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_PROXY_CVV_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_BNPL_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_BNPL_FAKE_DOOR_TEST), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_BNPL_V1_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_BNPL_CHECKOUT_BIN_VOUCHER);
        PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry payFeatureFlagsWithoutCountry = PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAY_BNPL_DASHBOARD_ENABLED;
        return SequencesKt___SequencesKt.toList(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(SequencesKt___SequencesKt.plus(plus, payFeatureFlagsWithoutCountry), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.DESIGN_SYSTEM_CHIPS_RIDER_TIP), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAY_BNPL_AD_HOC_ENABLED), payFeatureFlagsWithoutCountry), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAY_QPAY_DEFLECTION_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAY_BNPL_TALABAT_TRACKER_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAY_QPAY_ADD_CARD_DEFLECTION_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAY_QPAY_SAVED_CARD_DEFLECTION_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAY_QPAY_WALLET_DEFLECTION_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAY_ANDROID_FLUTTER_WALLET_ADD_CARD_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAY_ANDROID_FLUTTER_BNPL_DASHBOARD_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAY_ANDROID_FLUTTER_BNPL_CHECKOUT_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAY_QPAY_FALLBACK_ENABLED), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAYMENT_REPO_REAL_CARD_TOKENS), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.PAYMENT_REPO_REAL_PUBLIC_KEY), PayFeatureFlagConstants.PayFeatureFlagsWithoutCountry.WALLET_DASHBOARD_ONBOARDING_ENABLED));
    }
}
